services:
  main:
    build:
      context: ${CONTEXT_DIR}
    image: ${MAIN_IMAGE_NAME}
    command: [ "sh", "-c", "sleep infinity" ]
    network_mode: host
    environment:
      - TEST_DIR=${TEST_DIR}
      - TAC_SERVER_HOSTNAME=localhost
      - DECRYPTION_KEY=theagentcompany is all you need
    volumes:
      - ${HOST_VERIFIER_LOGS_PATH}:${ENV_VERIFIER_LOGS_PATH}
      - ${HOST_AGENT_LOGS_PATH}:${ENV_AGENT_LOGS_PATH}
